# Generated by Django 5.0.4 on 2024-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('SKU', models.CharField(max_length=50, unique=True)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Supplier', models.CharField(max_length=100)),
            ],
        ),
    ]
