# Generated by Django 5.0.4 on 2024-08-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='SKU',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Supplier',
            new_name='supplier',
        ),
    ]
